# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
  repositories:
    - repository: templates
      type: github
      name: # The name of the repository in github
      endpoint: # The name of thservice connection to the github

variables:
  dockerRegistryServiceConnection: # Container registry service connection established during pipeline creation i.e '094cdeb5-70ef-4fdc-b459-695a72c88709'.
  imageRepository: # The name of the image repository that will be created in the azure container registry i.e 'MyImageRepository'.
  containerRegistry: # The name of the azure container registry i.e '**.azurecr.io'.
  dockerfilePath: # The full path to the Dockerfile i.e '$(Build.SourcesDirectory)/**/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- template: docker-build-push.yml@templates
  parameters:
    vmImageName: $(vmImageName)
    imageRepository: $(imageRepository)
    dockerfilePath: $(dockerfilePath)
    dockerRegistryServiceConnection: $(dockerRegistryServiceConnection)
    tag: $(tag)