parameters:
  - name: vmImageName
    default: 'ubuntu-latest'
  - name: imageRepository
    default: ''
  - name: dockerfilePath
    default: ''
  - name: dockerRegistryServiceConnection
    default: ''
  - name: tag
    default: 'latest'   

stages:
- stage: Build
  displayName: Build and Push Docker Image Stage
  jobs:
  - job: Build
    displayName: Build and Push Docker Image to ACR
    pool:
      vmImage: ${{ parameters.vmImageName }}
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image to ACR
      inputs:
        command: buildAndPush
        repository: ${{ parameters.imageRepository }}
        dockerfile: ${{ parameters.dockerfilePath }}
        containerRegistry: ${{ parameters.dockerRegistryServiceConnection }}
        tags: |
          ${{ parameters.tag }}
