parameters:
  - name: vmImageName
    default: 'ubuntu-latest'
  - name: acruser
    default: ''
  - name: acrpassword
    default: ''
  - name: containerRegistry
    default: ''
  - name: chartPath
    default: 'latest'
  - name: chartArchiveFile
    default: ''
  - name: tag
    default: '1.0.0'

stages:    
- stage: Helm
  displayName: Helm Package and Push Stage
  jobs:
    - job: HelmPackageAndPush
      displayName: Helm Package and Push Artifacts to ACR
      pool: 
        vmImage: ${{ parameters.vmImageName }}
      steps:
      - script: |
          echo ${{ parameters.acrpassword }} | helm registry login ${{ parameters.containerRegistry }} -u ${{ parameters.acruser }} --password-stdin
        displayName: Login to ACR using Helm
      - script: |
          helm package --app-version ${{ parameters.tag }} --version ${{ parameters.tag }} ./${{ parameters.chartPath }}
        displayName: Package the chart directory into a chart archive
      - script: |
          helm push ${{ parameters.chartArchiveFile }} oci://${{ parameters.containerRegistry }}
        displayName: Push chart archive to ACR